name: Unit Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm install
      - name: tests
        continue-on-error: true
        run: npm test

      - name: test coveralls
        continue-on-error: true
        run: npm run test-coveralls

      - name: Publish coverage
        if: always()
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
